### ISSUE TITLE
Unexpected token M in JSON at position 0

### ISSUE THREAD

**Issue by wteoh** [yarivr/lp-labs-agent-sdk#10]
Hi yarivr,

I'm getting the follow error when i try to run my code with luis integration. The code ran perfectly fine previously. 

Any idea what has changed?

Thanks

SyntaxError: Unexpected token M in JSON at position 0
    at Object.parse (native)
    at Request._callback (C:\Users\wteoh\Documents\Sing Bot\node_modules\botbuilder\lib\dialogs\LuisRecognizer.js:70:39)
    at Request.self.callback (C:\Users\wteoh\Documents\Sing Bot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\wteoh\Documents\Sing Bot\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\wteoh\Documents\Sing Bot\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)

**Comment by wteoh** [comment]
i reinstalled lp-labs-agent-sdk using npm from and the issue still persist

**Comment by yarivr** [comment]
The original example was tested with luis API v1 which is now deprecated.
Can you verify that you initiated the LuisRecognizer to v2 (and with proper azure key)?
In recognizer-factory.js
You should init the LuisRecognizer like in bellow example:
 return new builder.LuisRecognizer('https://api.projectoxford.ai/luis/v2.0/apps/' + settings.id + '?subscription-key=' + settings.key);

**Comment by wteoh** [comment]
thanks yarivr, that solved the error. But it seems like its still not able to return the intent from LUIS as it is always going to the "None" dialog. Are there any changes required in botty.js?

Appreciate your help

**Comment by wteoh** [comment]
thanks it works
